### ISSUE TITLE
Support TRIGGER

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/sqldef#11]
## Problem
We can't specify TRIGGER in input DDLs.

### Initial schema
```
CREATE TABLE users (
  id bigint NOT NULL,
  name text
);

CREATE TRIGGER test BEFORE INSERT ON users
FOR EACH ROW SET name = concat(name, ".");
```

### Input DDLs
```
CREATE TABLE users (
  id bigint NOT NULL,
  name text
);

CREATE TRIGGER test BEFORE INSERT ON users
FOR EACH ROW SET name = concat(name, ".");
```

### Output DDLs
```
-- Nothing is modified --
```

**Comment by touyu** [comment]
Are you planning to implement this in the future?

**Comment by k0kubun** [comment]
Not planned, but I can say at least I still want this feature. So I'd implement it when it becomes critical for me, but if you're planning to implement it in a near term, I'd accept your patch.

**Comment by k0kubun** [comment]
Thanks, @ytakaya! https://github.com/k0kubun/sqldef/pull/135
