### ISSUE TITLE
Considering Graceful Shutdown

### ISSUE THREAD

**Issue by johejo** [k0kubun/sqldef#110]
## Background

Using sqldef to do relatively large migrations (which take at least 10 seconds) is not uncommon for enterprise users of sqldef.
I would like to consider how sqldef should behave in sudden interrupttions.

Database maintenance is often a sensitive task and is often a manual task (or chat-ops?). Interrupts on the local machine or working server should be considered.

Some users may be running Migration as a Pod on Kubernetes, not just running from a local machine.
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
So we should handle SIGTERM properly in addition to SIGINT(Ctrl-C).

## Possible behavior

There are several options.

**A. Check the signal at the some turning point and stop working when handling it.  But No signal handling during query execution.**
The migration may be executed halfway.

**B. In addition to A, propagate context.Context cancel to the DB driver using singla.NotifyContext added in go1.16.**
Advanced version of A.
The result depends on the implementation how the driver handles context.Context cancel.
The migration may be executed halfway.

**C. If the signal is caught during migration, rollback before migration.**
It seems very safe
This would be possible using ACID transactions.
But some DDLs in MySQL with InnoDB cannot rollback.
https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

## For our reference

golang-migrate/migrate handles SIGINT.
A detailed stop check is performed during migration execution.
https://github.com/golang-migrate/migrate/blob/master/internal/cli/main.go
https://github.com/golang-migrate/migrate/blob/master/migrate.go

Probably the behavior of golang-migrate/migrate is A.
This seems reasonable.
- golang-migrate/migrate existed before context.Context was added to Go.
- golang-migrate/migrate supports databases those do not guarantee ACID.

**Comment by k0kubun** [comment]
> I would like to consider how sqldef should behave in sudden interruptions.
> Interrupts on the local machine or working server should be considered.
> So we should handle SIGTERM properly in addition to SIGINT(Ctrl-C).

What problem you're trying to solve is unclear to me. You described three solutions without clarifying the problem they will solve.

Can you describe simple steps to reproduce an issue you're trying to fix, what unexpected consequence is caused by that, and what is the expected behavior for the scenario?

**Comment by johejo** [comment]
Oh ... Completely my mistake
sqldef already using transactions. 

How about logging the message "Interrupted! Doing rollback the database"?
But It may be better to be silent(current impl) as the behavior may be different for each DBMS.
The current behavior of sqldef is sufficient to me.  Thank you.
