### ISSUE TITLE
Provide ability to Enable/Disable SSL  

### ISSUE THREAD

**Issue by kiran94** [k0kubun/sqldef#12]
Currently when I attempt a command like: 

```sh
./psqldef -U $USER -W $PASSWORD $DATABASE --export
```
I get the following: 

```sh
2018/09/10 05:17:01 pq: SSL is not enabled on the server
```

It looks like this is happening because I do not have SSL setup on my postgres instance however I would like to have the ability to disable this from the client side. Based on https://stackoverflow.com/a/21959214 it looks like this is a simple change to 

https://github.com/k0kubun/sqldef/blob/d5ab266ee2f71df1613432d7c65323a7fa942270/adapter/postgres/postgres.go#L21

**Comment by k0kubun** [comment]
I supported to specify sslmode using `$PGSSLMODE` in v0.4.1. Could you try that once Travis releases the version?
