### ISSUE TITLE
export fails when the database contains a view

### ISSUE THREAD

**Issue by andym** [k0kubun/sqldef#14]
Using version v0.4.2. 

`./mysqldef -pmypass --export mydatabase`

Fails with 

`2018/10/01 13:03:22 sql: expected 4 destination arguments in Scan, not 2`

If mydatabase contains a view.

**Comment by k0kubun** [comment]
Yeah, that's not implemented yet. Would you like to manage the view in sqldef, or is it fine to just ignore the view for now?

**Comment by andym** [comment]
Ideally I'd like sqldef to manage the view, but I've just read the mysql docs about mysqldump + views, and it's more complicated than I expected. You'd also have to deal with pg views / manifest views and... all that.

I think for now just ignoring them with a warning is more useful than failing with runes.

**Comment by k0kubun** [comment]
Thanks for your understanding. Changed to ignore views for now, on v0.4.3.
