### ISSUE TITLE
Scan Error on column - converting NULL to string is unsupported

### ISSUE THREAD

**Issue by andrewmcfaul** [k0kubun/sqldef#154]
I have a production schema which gives the following error when I run mysqldef.

`Scan error on column index 5, name "Created": converting NULL to string is unsupported`

If I copy just the schema, but no data in a new instance, everything works fine.
If I copy the schema and data to a new instance I get the same error.
If I start truncating tables one at a time in the duplicated instance it will eventually start working.

I suspect that when the data size gets over a certain threshold we start to see this error. Maybe something to do with integer types and ranges causing a problem with large numbers?

**Comment by k0kubun** [comment]
Could you please file an issue following the issue template? I don't get what you want this time.

**Comment by andrewmcfaul** [comment]
I have captured the root of the issue and reopened as #157

**Comment by k0kubun** [comment]
Thanks! I appreciate that you figured out "MySQL < 5.7.2" because mysqldef already has working trigger tests and it would be hard to figure that out myself.

**Comment by andrewmcfaul** [comment]
No problem. It was my first time setting up a Go environement and project so it was a lot of fun diagnosing the issue.
