### ISSUE TITLE
Cannot parse fields or complex expressions in generated columns

### ISSUE THREAD

**Issue by andrewmcfaul** [k0kubun/sqldef#169]
When comparing schemas with generated columns, the comparison has an error if a field is specified using backticks or if the expression includes artithmetic operators like addition, division etc. This is similar to #153 but it only dealt with simple string values in the generated column expression.

## Input SQL
CREATE TABLE `test_generated` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `log_ins` int(11) NOT NULL DEFAULT '0',
  `user_count` int(11) NOT NULL DEFAULT '0',
  `log_ins_per_user` float GENERATED ALWAYS AS (`log_ins` / `user_count`) VIRTUAL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

## Current output
found syntax error when parsing DDL "CREATE TABLE `test_generated` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `log_ins` int(11) NOT NULL DEFAULT '0',
  `user_count` int(11) NOT NULL DEFAULT '0',
  `log_ins_per_user` float GENERATED ALWAYS AS (`log_ins` / `user_count`) VIRTUAL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8": syntax error at position 217 near 'log_ins'

## Expected output
Any valid expression should be allowed, including fields specified with backticks, operators like +, -, *, /, (, ), <, >, =, >=, <= and common SQL functions like CONCAT() etc.

**Comment by k0kubun** [comment]
Fixed the reported case at v0.11.12. Thank you.
