### ISSUE TITLE
MySQL can't parse Triggers when comparing schemas

### ISSUE THREAD

**Issue by andrewmcfaul** [k0kubun/sqldef#170]
When comparing two schemas that contain a trigger definition, the comparison fails with an error.

## Input SQL
```
CREATE TABLE `test_trigger` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TRIGGER BEFORE_UPDATE_test_trigger
BEFORE INSERT
ON test_trigger FOR EACH ROW BEGIN
SET NEW.`id` = NEW.`id` + 10;
END;
```

## Current output
found syntax error when parsing DDL "CREATE TRIGGER BEFORE_UPDATE_test_trigger
BEFORE INSERT
ON test_trigger FOR EACH ROW BEGIN
SET NEW.`id` = NEW.`id` + 10": syntax error at position 91 near 'begin'

## Expected output
It should parse the trigger definitions

**Comment by k0kubun** [comment]
I made the test case parsable in v0.11.13.
