### ISSUE TITLE
Can't parse CREATE TYPE statement when using psqldef

### ISSUE THREAD

**Issue by kawamurakazushi** [k0kubun/sqldef#171]
First of all, `--export` wasn't able to export `CREATE TYPE` statement.
After adding the `CREATE TYPE` statement, and running `--dry-run` it failed with syntax error.

## Input SQL

```sql
CREATE TYPE public.output_status AS ENUM ('reading', 'finished');
```

## Current output

```
syntax error at position 10 near 'TYPE'
```

## Expected output

expected to finish without any syntax error.

**Comment by k0kubun** [comment]
Fixed the reported case at v0.11.14.
