### ISSUE TITLE
Cannot use boolean literal as default value with psqldef

### ISSUE THREAD

**Issue by yuku** [k0kubun/sqldef#177]
## --export output
```sql
CREATE TABLE public.test (
    "col" boolean DEFAULT true
);
```

## Input SQL
```sql
CREATE TABLE test (
  "col" BOOLEAN DEFAULT FALSE
);
```

## Current output
Fail with `unsupported default value type (valueType: '7')`.

Note that migrating from `false` → `true` also fails with the same error.

## Expected output
Successfully migrate the schema.

## Workaround
Using string representations for the boolean works as expected:

```sql
CREATE TABLE test (
  "col" BOOLEAN DEFAULT 'false' -- or 'no', 'off', '0'
);
```

ref: https://www.postgresql.org/docs/14/datatype-boolean.html

**Comment by k0kubun** [comment]
Thanks for the report. Fixed in v0.11.16.
