### ISSUE TITLE
Support on delete cascade inline on postgres

### ISSUE THREAD

**Issue by jniclas** [k0kubun/sqldef#184]
Hey, 

is it possible to support ON DELETE CASCADE in an inline REFERENCE statement?

## --export output
```
-- No table exists --
2022/01/20 21:45:52 postgres: no tables found in database
```
## Input SQL
```
CREATE TABLE customers (
  id UUID NOT NULL PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
  id UUID NOT NULL PRIMARY KEY, 
  order_number VARCHAR(255) NOT NULL,
  customer UUID REFERENCES customers(id) ON DELETE CASCADE
);
```
## Current output
```
found syntax error when parsing DDL "CREATE TABLE orders (
  id UUID NOT NULL PRIMARY KEY,
  order_number VARCHAR(255) NOT NULL,
  customer UUID REFERENCES customers(id) ON DELETE CASCADE
)": syntax error at position 147 near 'delete'
```

## Expected output
Creates an foreignkey with on delete cascade.

Best reagrds
Niclas

**Comment by k0kubun** [comment]
I ran out of today's time for https://github.com/k0kubun/sqldef/issues/183, so I didn't get to fix this today. Sorry.

Out of curiosity, how many other things do you think are missing in psqldef for your use case? I'd appreciate it if you can file all you need at once instead of gradually filing a few every day.

**Comment by jniclas** [comment]
Hello,
no problem, I'm glad you're fixing the problems so quickly. 

I am testing out how well the combination of psqldef and graphjin, both as go library work together.
What I still have to test is full-text search, where I need a tsvector type column: https://github.com/dosco/graphjin/wiki/Detailed-Start#full-text-search 
```
CREATE TABLE ... (
...
tsv tsvector GENERATED ALWAYS AS (to_tsvector('english', name) || to_tsvector('english',description)) STORED,
...);
CREATE INDEX index_products_on_tsv ON products USING GIN (tsv tsvector_ops);
```

and autocomplete, where the column needs an expression "text_pattern_ops" https://github.com/dosco/graphjin/wiki/Detailed-Start#autocomplete 
```
CREATE INDEX product_name_autocomplete_index ON products(name text_pattern_ops);
```
Apart from that, I haven't seen anything else that I need for it.
So far the libraries complement each other perfectly. Many thanks for the development of sqldef.

Best regards
Niclas
