### ISSUE TITLE
feature request: enable to prepend `SET ROLE`

### ISSUE THREAD

**Issue by yuku** [k0kubun/sqldef#192]
It is great if there is a way to insert `SET ROLE` before DDLs. For example, suppose `psqldef` has `--set-role` option:

```
$ psqldef -U github-actions@$PROJECT_ID.iam --set-role owner_role -f schema.sql db_name
-- Apply --
SET ROLE "owner_role";
CREATE TABLE ...
```

### motivation

In postgres, when a resource is created, it is owned by the user/role that executed the associated `CREATE` DDL. Since the owner has special rights to the resource, it is often necessary to control the ownership. If a `psqldef` user wants to set the `owner_role` as the owner of a newly created resource, he can do so by connecting to the postgres server as `owner_role`.

Unfortunately, I can't use `owner_role` directly because:

* My postgres server is running in Google Cloud SQL, and I'm migrating the database continuously using `psqldef` from GitHub Actions.
* To reduce the number of secrets that I need to manage, I want to use [OIDC](https://docs.github.com/en/enterprise-cloud@latest/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) and [IAM authentication](https://cloud.google.com/sql/docs/postgres/authentication) to connect to Cloud SQL.
* This means that I have to connect to the postgres server as a service account (e.g. `github-actions@PROJECT_ID.iam` ≠ `owner_role`)

### note

Since I'm relatively new to postgres, I may misunderstand the ownership of resources.

### related documents

* [PostgreSQL: Documentation: 14: SET ROLE](https://www.postgresql.org/docs/14/sql-set-role.html)

**Comment by yuku** [comment]
@k0kubun How do you think? If it looks go to you, I'll send a PR.

**Comment by k0kubun** [comment]
I'm okay with accepting that feature. Alternative options that I thought of are:

* Have an option to prepend some DDLs when changes are applied. But I can't think of a good name for the option.
* Include `SET ROLE "owner_role";` in the schema file, and execute that only when changes are detected for other DDLs. But I'm not sure you want to use the same role in your local environment as well. In that case, your original proposal might be more helpful for you.

**Comment by yuku** [comment]
> Have an option to prepend some DDLs when changes are applied.

👍 In my case, I install [`pgcrypto` extension](https://www.postgresql.org/docs/current/pgcrypto.html) to my database in order to use `gen_random_bytes()`. If `psqldef` allows me to insert any SQL, I'd like to insert `CREATE EXTENSION IF NOT EXISTS "pgcrypto";` too.

> But I can't think of a good name for the option.

How about `--alter-epilogue`?

**Comment by yuku** [comment]
> Include SET ROLE "owner_role"; in the schema file, and execute that only when changes are detected for other DDLs. But I'm not sure you want to use the same role in your local environment as well.

This approach also works for me. However, I'm concerned that if we adopt this approach, we will need to add many lines to parser.y just for this feature, which will result in worse maintainability. 🤔

**Comment by k0kubun** [comment]
> This approach also works for me. However, I'm concerned that if we adopt this approach, we will need to add many lines to parser.y just for this feature, which will result in worse maintainability.

Agreed with the idea for things like `SET ROLE`. However,

> If psqldef allows me to insert any SQL, I'd like to insert CREATE EXTENSION IF NOT EXISTS "pgcrypto"; too.

I think extensions could be part of sqldef control. It doesn't matter in this issue though. I feel this could be still useful for other `SET` commands.

> How about --apply-epilogue?

The general principle of sqldef is to use the original options name if it exists. Thus I thought about using `-c`, but it could be just confusing. We'd probably need to use an original one.

I think you meant `--apply-prologue` (or `--apply-prelude`) because it needs to be executed first rather than at the end IIUC. For simplicity, I also thought about `--before-apply`. WDYT?

**Comment by yuku** [comment]
> I think extensions could be part of sqldef control.

👍 

> I think you meant `--apply-prologue`

oh, you're right 😅. And I agree with `--before-apply`.

The `--before-apply` option accepts a string (not a path to a file), right?

**Comment by k0kubun** [comment]
Yes, that's what I imagined. It should be used only for setting one or several `SET` commands. If something requires many lines and a file seems more useful for it, it should be supported in the input schema file.
