### ISSUE TITLE
feature request: disable stdout from schema migration

### ISSUE THREAD

**Issue by yujiG** [k0kubun/sqldef#198]
Hi, thanks for great project

I have an idea that is "disable stdout".  
for example I want to use `--no-stdout` option, like below

```sh
$ mysqldef -uroot test  --no-stdout > schema.sql
```

# motivation
We are using this library but our MySQL has 93 tables and there is an output of 1130 lines from `mysqldef`.  
If you approve this option our develop and test  environment would improve.  

How did you think?  
If you don't have time, I'll send PR!

**Comment by k0kubun** [comment]
I'm not sure if I understand your proposal. Is it different from "mysqldef -uroot test < schema.sql > /dev/null"?

**Comment by k0kubun** [comment]
From your description, it seems like you want to suppress the long output of applying your schema for the first time. If my understanding is correct, `mysqldef -uroot test < schema.sql > /dev/null` should work as you wanted. You could use `["bash", "-c", "mysqldef -uroot test < schema.sql > /dev/null"]` as a command of CI or docker-compose.

P.S. In case you don't like using redirection twice, you could also use `mysqldef -uroot test --file schema.sql > /dev/null`.
