### ISSUE TITLE
[mysqldef]feature request: ignore view option

### ISSUE THREAD

**Issue by tatsuo48** [k0kubun/sqldef#214]
Version: MySQL5.6.24

In my use case I want to apply one schema file to multiple schemas.
I want them all to have the same schema definition.

The exported schema file has a view, which contains the schema name.
export exmaple:
` mysqldef -h 0.0.0.0 -uroot -p schema1 --export > schema.sql`
```sql
CREATE TABLE `a` (
  `id` int(6) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE VIEW a_view AS
SELECT
	`schema1`.`a`.`id` AS `id`,
	`schema1`.`a`.`name` AS `name`
FROM
	`schema1`.`a`;
```

If you apply this schema file to another schema, it will be considered a diff because the schema names are different.
apply other schemas exmaple:
` mysqldef -h 0.0.0.0 -uroot -p schema2  < schema.sql`
```sql
CREATE TABLE `a` (
  `id` int(6) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE VIEW a_view AS select `schema1`.`a`.`id` AS `id`,`schema1`.`a`.`name` AS `name` from `schema1`.`a`;
```

If possible, it would be nice if the schema name in the view was replaced as follows.
```sql
CREATE TABLE `a` (
  `id` int(6) NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE VIEW a_view AS select `schema2`.`a`.`id` AS `id`,`schema2`.`a`.`name` AS `name` from `schema2`.`a`;
```

Or it would be nice to have the option to ignore the view when exporting or applying for such cases.
Would you consider adding an option?

**Comment by k0kubun** [comment]
This sounds like a reasonable problem to be solved. Though I think the final resolution should not be an option but something like: if you do not specify database names in a view definition, sqldef will assume the abbreviated database name is the database you're connected to, as it should. You would still have to manually remove the database name in an exported schema to activate the feature, but I feel it'd be the most convenient interface.

However, I need some time to implement that solution. So, meanwhile, I'm okay with temporarily providing an option to ignore views at all. Just to confirm what you want, let's say there's `--ignore-view` option in mysqldef, is that what you originally proposed? In other words, are you okay with maintaining the schema of views outside sqldef in the meantime?

**Comment by tatsuo48** [comment]
Thank you for your quick reply, and, Thank you for your consideration!

> Though I think the final resolution should not be an option but something like: if you do not specify database names in a view definition, sqldef will assume the abbreviated database name is the database you're connected to, as it should.

I have exactly the same opinion.

>  Just to confirm what you want, let's say there's --ignore-view option in mysqldef, is that what you originally proposed? In other words, are you okay with maintaining the schema of views outside sqldef in the meantime?

Yes!
In my case, view is managed by another mechanism, so you can have sqldef ignore it.

**Comment by k0kubun** [comment]
Introduced `--skip-view` option in v0.11.43.

**Comment by tatsuo48** [comment]
Thank you for adding this option.
I will use it immediately.
