### ISSUE TITLE
[mysqldef]feature request: `SET FOREIGN_KEY_CHECKS = 0;` before apply

### ISSUE THREAD

**Issue by tatsuo48** [k0kubun/sqldef#215]
Executing SET FOREIGN_KEY_CHECKS = 0 seems to solve the following two problems.

## Table cannot be created if there is a foreign key constraint on the table before creation
this is same problem: https://qiita.com/abe_masanori/items/7fd2a470e7eba2f255a4#3-1---export%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E3%82%88%E3%82%8B%E3%83%AA%E3%83%90%E3%83%BC%E3%82%B9%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%AA%E3%83%B3%E3%82%B0

```sql
CREATE TABLE `a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `a` FOREIGN KEY (`b_id`) REFERENCES `b` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```

Table `a` cannot be created because it has a foreign key constraint on table `b` before it was created.
mysqldef output:
```
-- Apply --
CREATE TABLE `a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `a` FOREIGN KEY (`b_id`) REFERENCES `b` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
2022/03/06 11:22:06 Error 1215: Cannot add foreign key constraint
```

## Unable to create a table that cross-references foreign keys.
I have two tables with foreign key constraints on each other.
```sql
CREATE TABLE `a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `a` FOREIGN KEY (`b_id`) REFERENCES `b` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE `b` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `b` FOREIGN KEY (`a_id`) REFERENCES `a` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```

With the current mysqldef, if you try to create a schema based on this schema file, you cannot create a table due to cross-reference.
mysqldef output:
```
-- Apply --
CREATE TABLE `a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `a` FOREIGN KEY (`b_id`) REFERENCES `b` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
2022/03/06 11:22:06 Error 1215: Cannot add foreign key constraint
```

These problems can be solved if you can set `SET FOREIGN_KEY_CHECKS = 0;` before executing the SQL.
I would like to send the same changes to mysqldef as the PR for https://github.com/k0kubun/sqldef/pull/195.
What do you think of this change?

**Comment by k0kubun** [comment]
Adding the same feature as https://github.com/k0kubun/sqldef/pull/195 to mysqldef is fine with me. I'll accept your PR.

This should probably work without it, but I'm still not sure if we should support applying DDLs that cannot be applied to the database as is by letting sqldef separately generate CREATE TABLE and ADD FOREIGN KEY. I guess, if supporting it is not terribly complicated, I would probably support it assuming those users want to declaratively define everything rather than keeping the compatibility of raw DDLs.
