### ISSUE TITLE
psqldef: error occurs if cast in check constraint

### ISSUE THREAD

**Issue by bubusuke** [k0kubun/sqldef#219]
Hi I fixed parse in check constraint.

A Parse error will occur if the CHECK constraint contains CAST as shown below.
```SQL
    CREATE TABLE test (
      col text NOT NULL CHECK (col <> ''::text)
    );
```

error is.
```
found syntax error when parsing DDL "CREATE TABLE test (
          col text NOT NULL CHECK (col <> ''::text)
        )": syntax error at position 63 near 'text'
```

---

I think the cause is insufficient CAST support when parsing Value.

**Comment by k0kubun** [comment]
merged https://github.com/k0kubun/sqldef/pull/220. thanks!
