### ISSUE TITLE
[mysqldef] syntax error on unique index

### ISSUE THREAD

**Issue by tmokmss** [k0kubun/sqldef#225]
Hi team, thanks for developing this great software! I found a weird behavior below. Could you check this when you get a chance? Thanks!

## --export output
n/a

## Input SQL
```sql
CREATE TABLE items (
    id int NOT NULL,
    created DATE NOT NULL,
    UNIQUE INDEX(id, created)
);
```

## Current output
```
found syntax error when parsing DDL \"CREATE TABLE items (\n    id int NOT NULL,\n    created DATE NOT NULL,\n    UNIQUE INDEX(id, created)\n)\": syntax error at position 87\n",
```

## Expected output
no error returned since it's a valid SQL query.

**Comment by k0kubun** [comment]
Fixed in v0.11.46.
