### ISSUE TITLE
Support concurrent index builds in postgres

### ISSUE THREAD

**Issue by rockwotj** [k0kubun/sqldef#231]
Postgres has a great feature to support nonblocking index builds, this is a must have for postgres index builds on an existing production table.

## --export output
```
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer'
);
```
## Input SQL
```
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT 'konsumer'
);
CREATE INDEX username on user (name);
```
## Current output

```
CREATE INDEX username on user (name)
```

## Expected output
```
CREATE INDEX CONCURRENTLY username on user (name)
```

**Comment by k0kubun** [comment]
While there are a few downsides to `CREATE INDEX CONCURRENTLY`, such as slowing down the operations by waiting for the completion of in-progress updates and doubling the number of table scans, it's probably not a big impact on development environments and the behavior would be justified in production for most cases. So I'll make it the default behavior for PostgreSQL.

**Comment by k0kubun** [comment]
> pq: CREATE INDEX CONCURRENTLY cannot run inside a transaction block

:thinking:

**Comment by k0kubun** [comment]
I slightly transformed the requirement. In order to give some flexibility, I just supported parsing `CREATE INDEX CONCURRENTLY` so that it's used only when it's specified as such. Please try v0.11.51 with `CREATE INDEX CONCURRENTLY` in your input SQL, not just `CREATE INDEX`.

**Comment by rockwotj** [comment]
This is wonderful thank you 🙏
