### ISSUE TITLE
[psqldef] the parser can not parse the "CREATE INDEX" statement without the index name

### ISSUE THREAD

**Issue by kenkoooo** [k0kubun/sqldef#234]
## --export output
```sql
CREATE TABLE "public"."user" (
    "id" bigint NOT NULL
);
```

## Input SQL
```
CREATE TABLE "user" (id BIGINT NOT NULL);
CREATE INDEX ON "user" (id);
```

## Current output
```
found syntax error when parsing DDL "CREATE INDEX ON "user" (id)": syntax error at position 16 near 'on'
```

## Expected output
```
-- Apply --
CREATE INDEX ON "user" (id);
```

## Report

I found the above error when I was trying to create an index without the index name with psqldef v0.11.53. I confirmed that I could create that index when I explicitly gave the index name.

**Comment by k0kubun** [comment]
Fixed in v0.11.55.
