### ISSUE TITLE
Adding foreign key into "variables" table cause error

### ISSUE THREAD

**Issue by yuonoda** [k0kubun/sqldef#249]
Thank you for making this useful tool. 
I found that adding foreign key into some tables cause unexpected error.
I met this issue when I add foreign key constraint onto "variables" table.

This should be because "variables" is treated as a reserved word and quoted unpropery.
When I comment out a line bellow, it worked well.
https://github.com/k0kubun/sqldef/blob/7a72653fcb5d0e2ac1e52c0d46571c8cc88e0e1b/parser/token.go#L442

I think word "variables" is a reserved word in MySQL, But not in PostgreSQL.
So I expected to use "variables" table in my PostgreSQL database.

This is really minor issue and I can change the table name not to collide with reserved keywords.
I reported this issue for you and other users' information.

Thanks.

## --export output

```sql
CREATE TABLE "public"."variables" (
    "id" character varying(100) NOT NULL,
    "compaby_id" character varying(100) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."users" (
    "id" character varying(100) NOT NULL,
    "variable_id" character varying(100) NOT NULL,
    "name" character varying(100),
    PRIMARY KEY ("id")
);
```

## Input SQL
```sql

CREATE TABLE IF NOT EXISTS variables (
    id VARCHAR(100) PRIMARY KEY,
    compaby_id VARCHAR(100) NOT NULL REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(100) PRIMARY KEY,
    variable_id VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    CONSTRAINT users_variable_id_fk FOREIGN KEY (variable_id) REFERENCES variables(id)
);
```

## Current output
```
-- Apply --
ALTER TABLE "public"."users" ADD CONSTRAINT "users_variable_id_fk" FOREIGN KEY ("variable_id") REFERENCES "public"."`variables`" ("id");
2022/06/23 15:46:54 pq: relation "public.`variables`" does not exist
exit status 1
```

## Expected output
```
-- Apply --
ALTER TABLE "public"."users" ADD CONSTRAINT "users_variable_id_fk" FOREIGN KEY ("variable_id") REFERENCES "public"."variables" ("id");

```

**Comment by k0kubun** [comment]
Fixed in v0.11.61.
