### ISSUE TITLE
syntax error when parse materialized view ddl in postgres

### ISSUE THREAD

**Issue by uqichi** [k0kubun/sqldef#262]
Thank you for your development.
I have a problem when executed `sqldef.Run(schema.GeneratorModePostgres, db, options)` with `schema.sql`
Maybe materialized view is not supported for now?

## Input SQL
```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS points_view AS
    SELECT id FROM points;
```
## Current output
```
found syntax  when parsing DDL "CREATE MATERIALIZED VIEW IF NOT EXISTS points_view AS
SELECT id FROM points": syntax  at position 20 near 'MATERIALIZED'
```

## Expected output
No errors.

**Comment by k0kubun** [comment]
Introduced materialized views support for psqldef at v0.12.5.
