### ISSUE TITLE
Export unique_idx error

### ISSUE THREAD

**Issue by ego** [k0kubun/sqldef#284]
`psqldef` with  flag `--export ` raise error:
```found syntax error when parsing DDL "CREATE UNIQUE INDEX airline_confirmation_code_unique_idx ON public.airline_confirmation USING btree (airline_id, booking_id, lower((code)::text)) WHERE ((code IS NOT NULL) AND (airline_id IS NOT NULL))": syntax error at position 133```

**Comment by k0kubun** [comment]
When you report an issue, can you provide a working schema to reproduce it? Running the SQL fails on `psql` as well (ERROR: relation "public.airline_confirmation" does not exist).

**Comment by ego** [comment]
Hi, check with this simple table and index:
```sql
CREATE TABLE public.airline_confirmation (
    airline_id bigint,
    code character varying(512),
    booking_id bigint NOT NULL
);

CREATE UNIQUE INDEX airline_confirmation_code_unique_idx 
    ON public.airline_confirmation 
    USING btree (airline_id, booking_id, lower((code)::text)) 
    WHERE ((code IS NOT NULL) AND (airline_id IS NOT NULL));
```
