### ISSUE TITLE
pg_dump error showing only "exit status 1" makes it hard to understand the cause

### ISSUE THREAD

**Issue by sonken625** [k0kubun/sqldef#29]
psqldefを利用している際に、一度psqldefを利用してテーブルを作った後exit status 1が出力されて終了してしまう問題があり、調べたところpg_dumpのバージョン違いでpg_dumpがエラーを履いていました。

pg_dumpはテーブルを作った後でないと呼び出されないので一度目はうまく動いてしまったというのと、エラー文がexit status 1のみ出力されるため気づくのが難しかったため、`adapter#runPgDump()`内にある`Cmd.Output()`を`CombinedOutput()`とし、エラー文に追加するよう書き換えたのですがプルリクを送ってもよろしいでしょうか？

**Comment by k0kubun** [comment]
ご報告ありがとうございます。exit status 1だけだと不便だと思いますので、方針良さそうに思います。実際の変更を見て判断したいので、プルリクエストを送る前に許可を取っていただく必要はございません。

**Comment by k0kubun** [comment]
Resolved in https://github.com/k0kubun/sqldef/pull/30
