### ISSUE TITLE
Windows executable file does not have .exe extension

### ISSUE THREAD

**Issue by ciffelia** [k0kubun/sqldef#293]
Hi, I just downloaded `sqlite3def_windows_amd64.zip` from the releases page and noticed that the executable file is missing `.exe` extension, thus can't be executed. Renaming `sqlite3def` to `sqlite3def.exe` solved the issue.
I guess there's something wrong in the release workflow and the extension is removed from executables.

**Comment by k0kubun** [comment]
The workflow doesn't rename the executable. It's just how `go build` works, I suppose. We could let the build pipeline add .exe instead.

**Comment by ciffelia** [comment]
I see. I'll create a PR.
