### ISSUE TITLE
psqldef: Support options parameter

### ISSUE THREAD

**Issue by ohkinozomu** [k0kubun/sqldef#295]
I use [CockroachDB Serverless](https://www.cockroachlabs.com/lp/serverless/) and its [compatibility](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html) with PostgreSQL is excellent.
I would like to use sqldef there.

CockroachDB Serverless requires the connection to specify the cluster in the `options` parameter.
https://www.cockroachlabs.com/docs/stable/connection-parameters.html#supported-options-parameters
https://www.postgresql.org/docs/15/libpq-connect.html#LIBPQ-PARAMKEYWORDS

Currently the `options` parameter is [not supported](https://github.com/k0kubun/sqldef/blob/5d45c5ac87f49a2861613a76ca604cbbeca15adc/database/postgres/database.go#L791-L813), is there a possibility to support it?

**Comment by k0kubun** [comment]
Do you know how `options` parameter could be passed with the `psql` command? `psqldef` tries to be compatible with `psql` as much as possible. If `psql` has an interface for it, we should implement it in the same way. Even if not, I'm open to an original flag for it. However, I don't have a CockroachDB Serverless environment to test it, so I need you to file a patch and test it yourself.

**Comment by ohkinozomu** [comment]
> Do you know how options parameter could be passed with the psql command?

With `PGOPTIONS`.
https://www.postgresql.org/docs/15/libpq-envars.html

And I apologize for my lack of checking: **psqldef v0.13.17 seems to support `PGOPTIONS`.**

```bash
$ PGSSLMODE='verify-full' PGOPTIONS='--cluster=[my cluster]' psqldef -h free-tier.gcp-us-central1.cockroachlabs.cloud -U [my user] -p 26257 -W [password] --export my_database
2022/11/02 15:11:18 syntax error at or near "ASC"
```

The error message is probably based on an incompatibility between PostgreSQL and CockroachDB, but the connection itself seems to work.

`parseEnviron` in lib/pq may allow this.
https://github.com/lib/pq/blob/v1.10.7/conn.go#L1977-L2047

This behavior somewhat unexpected, but this issue can be closed.

**Comment by k0kubun** [comment]
:eyes: I see, thanks for finding and checking it.

**Comment by ohkinozomu** [comment]
Incidentally, after digging into the error, I found that it is due to an incompatibility that unique indexes appear in pg_constraint. 
https://github.com/cockroachdb/cockroach/issues/65885

sqldef enthusiasts who are trying to migrate to CockroachDB shouldn't do so.
