### ISSUE TITLE
support MySQL 8.0 Generated Column

### ISSUE THREAD

**Issue by tomtwinkle** [k0kubun/sqldef#301]
Looking forward to support for Generated columns!
https://dev.mysql.com/doc/refman/8.0/en/create-table-generated-columns.html

## Platform

* OS: Linux
* RDBMS: MySQL
* Version: 8.0

## --export output

```
CREATE TABLE `samples` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `json_data` json NOT NULL,
  `json_name` varchar(20) GENERATED ALWAYS AS (json_extract(`json_data`,'$.foo_name')) VIRTUAL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

## Input SQL

Changes in the contents of columns referenced in GENERATED. `$.foo_name` -> `$.bar_name`.

```
CREATE TABLE `samples` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `json_data` JSON NOT NULL,
  `json_name` varchar(20) GENERATED ALWAYS AS (JSON_EXTRACT(`json_data`, "$.bar_name")) VIRTUAL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

## Current output

No change

## Expected output

```
ALTER TABLE `samples` DROP `json_name`;
ALTER TABLE `samples` ADD `json_name` varchar(20) GENERATED ALWAYS AS (JSON_EXTRACT(`json_data`, "$.bar_name")) VIRTUAL;
```

**Comment by k0kubun** [comment]
Can you write an example schema SQL you'd like to use? It's okay you didn't follow the issue template, but still, I always want to see an actual SQL instead of a reference to general features so that we don't need to support something that nobody uses.

**Comment by tomtwinkle** [comment]
Sorry.
I have included the details. Please check it.

**Comment by k0kubun** [comment]
Thanks for the update. Since sqldef seems to be parsing that syntax correctly, it might not be too difficult to fix. Part of [schema/generator.go](https://github.com/k0kubun/sqldef/blob/master/schema/generator.go) may be not detecting that kind of change. Would you be interested in working on a PR to fix it?

**Comment by tomtwinkle** [comment]
Thanks, I'll take a look.
