### ISSUE TITLE
Proposal: Add skip_tables option to config yaml.

### ISSUE THREAD

**Issue by kitagry** [k0kubun/sqldef#303]
Hi @k0kubun, thank you for the nice plugin!!

I'm using mysqldef with machine learning products, and I have the following approach for databaes.

1. create `tmp_scores` table
2. insert data into `tmp_scores`
3. rename `tmp_scores` to `scores`, and `scores` to `old_scores`
4. delete `old_scores`

This is because the ML data is very huge and we don't want to affect the system using the `scores` table.
So, I would like to add an `ignore_tables` option to the config yaml in order to ignore `tmp_scores`.

If you like this idea, I'll create PR. Thank you.

**Comment by k0kubun** [comment]
Sounds good. As to the name, what do you think about calling it `skip_tables`? We have a couple of `--skip-xxx` options and we'll likely move them to `skip_xxx` fields in the config file, so it might be a bit more consistent with it.

**Comment by kitagry** [comment]
Thank you for the quick reply!

> As to the name, what do you think about calling it skip_tables?

`skip_tables` seems to be better. Thank you.

I'll create PR in a few days!
