### ISSUE TITLE
Proposal: change current behavior for --file option

### ISSUE THREAD

**Issue by kitagry** [k0kubun/sqldef#322]
Hi @k0kubun. Thank you for the nice tool!

I would like to use the following schema.

```
./schema
├── common.sql  # for both production and test
├── production.sql
└── test.sql
```

I think it is natural to use `--file` option multiple, like the following.

```bash
mysqldef --file ./schema/common.sql --file ./schema/production.sql
```

But, currently `--file` option has other role. https://github.com/k0kubun/sqldef/pull/179.
I think it is a bit confusing, because file options have a different role and there is no document.

```diff
$ mysqldef --help
...
-      --file=sql_file                Read schema SQL from the file, rather than stdin (default: -)
+      --file=sql_file                Read schema SQL from the files, rather than stdin (default: -)
+      --current-file=sql_file        Read schema SQL file as current schema, rather than to connect DB
``` 

I would like to change the current option like above.
But, it is breaking change. So if you don't like this idea, please feel free to close this issue. Thank you.

**Comment by kitagry** [comment]
Yes, I know the way you propose, and it is very useful as CLI tool. But currently I use it in Kubernetes, and I want to use it as the following.

In Dockerfile, I use multiple target for test and production.

```dockerfile
FROM base AS test
ENTRYPOINT ["mysqldef", "--file", "common.yaml", "--file", "test.yaml"]

FROM base AS prod
ENTRYPOINT ["mysqldef", "--file", "common.yaml", "--file", "production.yaml"]
```

And, in kubernetes.yaml

```yaml
images: sqldef-sample  # we change only this image
args: ["-uroot", "test"]
```

Currently we should write file location in Kubernetes.yaml, but it is not beautiful because kubernetes.yaml should know where dockerfile puts schema file.

```yaml
images: sqldef-sample
command: ["sh", "-c"]
args: ['cat common.yaml production.yaml | mysqldef -uroot test'] # we should change this command, and this include file location information in Dockerfile.
```

If there is multiple `--file` option, I can write clean code for the above usecase. But this is your OSS, so please feel free to decide whether to adopt or not. :smile: Thank you!

**Comment by k0kubun** [comment]
Fair enough. Though, WDYT about supporting `["mysqldef", "--file", "common.yaml production.yaml"]` or `["mysqldef", "--file", "common.yaml,production.yaml"]`  instead? Specifying `"--file"` multiple times could feel redundant when you need three files or more. We could still support file names containing `" "` or `","` if we allow escaping it with `"\"`.

**Comment by kitagry** [comment]
> WDYT about supporting ["mysqldef", "--file", "common.yaml production.yaml"] or ["mysqldef", "--file", "common.yaml,production.yaml"] instead?

I think it is better than my proposal! Thank you!

**Comment by k0kubun** [comment]
:+1:

Would you be interested in filing a pull request for adding your feature?

**Comment by kitagry** [comment]
Yes! I'll send PR in a few days!

I have one confirmation. Would you mind if I change current schema option?

```diff
$ mysqldef --help
...
-      --file=sql_file                Read schema SQL from the file, rather than stdin (default: -)
+      --file=sql_file                Read schema SQL from the files, rather than stdin (default: -)
+      --current-file=sql_file        Read schema SQL file as current schema, rather than to connect DB
```

**Comment by k0kubun** [comment]
I think you don't need to break the backward compatibility if `--file` behaves like `--file "foo.sql bar.sql"`, but I'm okay with revising the interface if you want. However, because of the above `mysql` compatibility reasons, I'm generally reluctant to introduce any `mysql`-incompatible options. 

Instead of introducing `--current-file`, how about interpreting the current `db_name` part as a current schema file if it ends with `.sql`? For example, you can do `mysqldef current.sql < desired.sql` with that interface.
