### ISSUE TITLE
Cannot ALTER TABLE to add foreign key newly

### ISSUE THREAD

**Issue by tomocrafter** [k0kubun/sqldef#327]
## --export output
empty

## Input SQL
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;
```

## Current output
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
```

## Expected output
```sql
-- dry run --
CREATE TABLE posts (
  content text,
  user_id bigint
);
ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;
```

I investigated for couple hours and I figured out that seems like [generateDDLsForAddForeignKey](https://github.com/k0kubun/sqldef/blob/master/schema/generator.go#L674) does not generate ddl nor append to ddls.
following test fails even though it should pass.

```golang
func TestPsqldefAddForeignKeyA(t *testing.T) {
	resetTestDatabase()

	createUsers := "CREATE TABLE users (id BIGINT PRIMARY KEY);\n"
	createPosts := stripHeredoc(`
		CREATE TABLE posts (
		  content text,
		  user_id bigint
		);
		`,
	)
	addForeignKey := "ALTER TABLE ONLY public.posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE;\n"
	assertApplyOutput(t, createUsers+createPosts+addForeignKey, applyPrefix+createUsers+createPosts+addForeignKey)
}
```

**Comment by k0kubun** [comment]
> I investigated for couple hours and I figured out that seems like [generateDDLsForAddForeignKey](https://github.com/k0kubun/sqldef/blob/master/schema/generator.go#L674) does not generate ddl nor append to ddls.
> following test fails even though it should pass.

Thanks for investigating it! It seems like you know enough about why it's not working well for you. Can you make it a pull request? I'm open to supporting this use case.

**Comment by tomocrafter** [comment]
@k0kubun I really appreciate for reviewing!
I'm really new to sqldef and even golang. so I'd like to hear where should I change or read code for understand whole this project architecture.

**Comment by k0kubun** [comment]
I think you're actually on the right track; the current behavior of `generateDDLsForAddForeignKey` seems suspicious to me too. It's probably enough to look at the behavior of that function and its callers for understanding relevant behaviors.

I recommend using https://github.com/k0kubun/pp to look at the variables that it interacts with. Inserting `pp.Println(...)` to dump variables would be useful to debug why it's not working as expected. For doing so, create a PostgreSQL database first (the `docker-compose.yml` in this repository might be useful), and then run psqldef using `go run cmd/psqldef/psqldef.go`.
