### ISSUE TITLE
Table name with schema name is handled incorrectly.

### ISSUE THREAD

**Issue by odz** [k0kubun/sqldef#336]
If DDL has CREATE TABLE statement with schema name, output of `DROP TABLE`  statement with `dbo` schema.
I tested it with mssqldef, other RDBMS maybe has same problem.

## --export output

```sql
CREATE TABLE FOO.bigdata1 (
    data bigint
);

CREATE TABLE FOO.bigdata2 (
    data bigint
);
```

## Input SQL

```sql
CREATE TABLE FOO.bigdata1 (
    data bigint
);
```

## Current output

```
-- Apply --
DROP TABLE [dbo].[bigdata2];
2022/12/15 00:00:56 mssql: Cannot drop the table 'dbo.bigdata2', because it does not exist or you do not have permission.
```

## Expected output

```
DROP table [FOO][.bigdata2];
```

**Comment by k0kubun** [comment]
I'm not so familiar with SQL Server, so I'd like to delegate this to @ytakaya.
