### ISSUE TITLE
mssqldef: Support `Go` keywords.

### ISSUE THREAD

**Issue by odz** [k0kubun/sqldef#382]
Some tools used with SQL Server such as sqlcmd, SQL Server Management Studio requires `Go` keywords to separate batches and, `CREATE VIEW` and `CREATE TRIGGER` statements must be the first statement in a batch.
So, schema scripts are typically contains `Go` keywords, but mssqldef does not support `Go` keyword currently.

And, exported definitions also contains `Go` is desired.

## Platform

* OS: Linux (probably all)
* RDBMS: SQL Server
* Version: 0.15.22

## --export output

```
-- No table exists --
```

## Input SQL

```sql
CREATE TABLE [dbo].[departments] (
    [id] int NOT NULL,
    [name] text,
    CONSTRAINT [departments_pk] PRIMARY KEY CLUSTERED ([id])
);
Go

CREATE TABLE [dbo].[users] (
    [id] int NOT NULL,
    [name] text,
    [department_id] int,
    CONSTRAINT [users_pk] PRIMARY KEY CLUSTERED ([id])
);
Go

CREATE VIEW [dbo].[departments_view] AS
SELECT
    id,
    name,
    (SELECT COUNT(*) FROM users WHERE users.department_id = departments.id) AS user_count
FROM
    departments;
Go
```

## Current output

```
found syntax error when parsing DDL "Go

CREATE TABLE [dbo].[users] (
    [id] int NOT NULL,
    [name] text,
    [department_id] int,
    CONSTRAINT [users_pk] PRIMARY KEY CLUSTERED ([id])
);
Go

CREATE VIEW [dbo].[departments_view] AS
SELECT
    id,
    name,
    (SELECT COUNT(*) FROM users WHERE users.department_id = departments.id) AS user_count
FROM
    departments;
Go": syntax error at position 3 near 'Go'
```

## Expected output

```sql
-- Apply --
CREATE TABLE [dbo].[departments] (
    [id] int NOT NULL,
    [name] text,
    CONSTRAINT [departments_pk] PRIMARY KEY CLUSTERED ([id])
);
Go

CREATE TABLE [dbo].[users] (
    [id] int NOT NULL,
    [name] text,
    [department_id] int,
    CONSTRAINT [users_pk] PRIMARY KEY CLUSTERED ([id])
);
Go

CREATE VIEW [dbo].[departments_view] AS
SELECT
    id,
    name,
    (SELECT COUNT(*) FROM users WHERE users.department_id = departments.id) AS user_count
FROM
    departments;
Go
```

**Comment by odz** [comment]
If `Go` keywords are output in exported schema, is it breaking change?

**Comment by odz** [comment]
Yes, if `Go` is added in output, many test cases are breaks.
I'll think about that more. I might add command line options to indicate to output `Go` to keep backward-compatibility.

**Comment by k0kubun** [comment]
I said "it passes existing tests once you add `Go` to the test cases". Adding `Go` to test cases seems fine.

**Comment by odz** [comment]
Okay, I'll try it.
