### ISSUE TITLE
psqldef: failed to export schema with TimescaleDB

### ISSUE THREAD

**Issue by Pranc1ngPegasus** [k0kubun/sqldef#389]
## Platform

* OS: macOS
* RDBMS: PostgreSQL (TimescaleDB)
* Version: v0.15.22

## --export output

`--export` operation will fail.

## Input SQL

no DDL needed.

## Current output
```
found syntax error when parsing DDL "CREATE TABLE "_timescaledb_config"."bgw_job" (
    "id" serial NOT NULL,
    "application_name" name NOT NULL,
    "schedule_interval" interval NOT NULL, // <-- maybe position 144 is here.
    "max_runtime" interval NOT NULL,
    "max_retries" integer NOT NULL,
    "retry_period" interval NOT NULL,
    "proc_schema" name NOT NULL,
    "proc_name" name NOT NULL,
    "owner" regrole NOT NULL DEFAULT (CURRENT_ROLE)::regrole,
    "scheduled" boolean NOT NULL DEFAULT true,
    "fixed_schedule" boolean NOT NULL DEFAULT true,
    "initial_start" timestamp with time zone,
    "hypertable_id" integer,
    "config" jsonb,
    "check_schema" name,
    "check_name" name,
    "timezone" text,
    PRIMARY KEY ("id")
)": syntax error at position 144 near 'interval'
```

## Expected output

operation success.

**Comment by k0kubun** [comment]
It appears that @odz has been [working on this](https://twitter.com/odz/status/1651022482508480512) (Thank you!). I'll leave this to him to avoid duplicating the effort. Let me know if @odz needs help from me.

**Comment by odz** [comment]
This issue has several problems.

1. Tables, views and types created by extensions are exported by sqldef. These should not be exported.  It is also reported in #65 and #224.
2. The parser for postgres which uses pg_query_go fails to parse that contains DEFAULT option. In this case, tables created by timescaledb extension have DEFAULT option.
3. If the parser for postgres fails to parse sql, then sqldef switches a parser to the generic parser which comes from vitess.
    But this parser cannot parse "interval" column type. So, the error is reported at "interval."

For fixing this issue, solve the problem 1 is enough. I've tested the patch on my PC, so I'll send the PR soon.
