### ISSUE TITLE
sqlparser is MySQL specific.

### ISSUE THREAD

**Issue by stephenpaulger** [k0kubun/sqldef#4]
Examples for PostgreSQL only work if they use syntax that happens to be the same as MySQL's.

This SQL snippet will work in PostgreSQL

```sql
CREATE TABLE example_postgres_table (
    column_name bool
);
```

But attempting to use `psqldef` sadly doesn't work because `bool` isn't a keyword that sqlparser recognises.

```
% psqldef -U $DBUSER -h $DBHOST -p $DBPORT $DBNAME --dry-run < postgres-table.sql
found syntax error when parsing DDL "CREATE TABLE example_postgres_table (    column_name bool)": syntax error at position 58 near 'bool'
```

I didn't want to just add the keyword to sqlparser, as that would then allow incorrect SQL to be written for MySQL databases. I had a brief look for existing PostgreSQL parsers in Go but did not find one.

**Comment by k0kubun** [comment]
> I didn't want to just add the keyword to sqlparser, as that would then allow incorrect SQL to be written for MySQL databases

I get your point and thought the same thing before. In a perfect world, parser should be database-specific.

But in reality, even if data types or syntax for both databases are supported, when the query is executed on CI or development server, mysql or postgresql server will detect the syntax error. So at least in an early stage of development, my plan is to parse both syntax and it's currently working in that way.

**Comment by stephenpaulger** [comment]
I was just thinking about how I might go about doing a PR and suddenly you've done it 😃 

Thanks

**Comment by stephenpaulger** [comment]
Another example of where the two syntax's differ.

```sql
-- PostgreSQL syntax
CREATE TABLE example_postgres_table (
    "timestamp" timestamp
);

-- MySQL syntax
CREATE TABLE example_mysql_table (
    `timestamp` timestamp
);
```

**Comment by k0kubun** [comment]
okay, I'll think about whether we can switch the parser behavior or not, otherwise parse both for now.

**Comment by stephenpaulger** [comment]
The addition of parser modes in your recent commit seems a good choice.

If I find other examples of parsing issues that I can't fix for whatever reason would you prefer if I added failing tests, raise an issue or reply to this thread?

**Comment by k0kubun** [comment]
Failing tests in PR would be the most helpful for me, but raising another issue would be helpful too. 

I'm very thankful to your effort and attention to this tool :smiley:
