### ISSUE TITLE
I want an option that doesn't make disruptive changes.

### ISSUE THREAD

**Issue by touyu** [k0kubun/sqldef#43]
When developing with multiple people separately, if migration is performed for each, the table will be dropped.
Therefore I want an option that doesn't make destructive changes like Gorm's automigrate.

**Comment by k0kubun** [comment]
I'm basically open to merge https://github.com/k0kubun/sqldef/pull/44, but I'm not sure if I understand your situation correctly. 

I guess the situation is like:

1. There was a table "T" on master branch.
2. On a topic branch, a person "A" added a column "a" to the table "T".
3. On another topic branch, a person "B" added a column "b" to the table "T".

In this situation, step 3 would unintentionally drop the column "a". Therefore you'd like to use the `--safety` option on step 2 or 3, and you'd run schema migrations without `--safety` only when you really want to drop a column. Is my understanding correct?

**Comment by touyu** [comment]
Yes, your understanding is correct.
I assume the similar situation.
