### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by konsumer** [k0kubun/sqldef#45]
Hi, I am new to go, and use nodejs mostly.

I am interested in compiling this awesome project as a wasm library, so It can be used on the web & in node (I am thinking it would be an awesome alternative to [knex](http://knexjs.org/) migrations.) wasm is cross-platform, so I imagine it would be a great way to distribute it for javascript targets (rather than node-only compiled library / exec calls to CLI.) It also opens up the possibility of using it in [lots of other languages](https://github.com/wasmerio/wasmer).

In my naivety, I just changed `GOOS=js` and `GOARCH=wasm` in Makefile, but I get this error when I run `make`:

```
# github.com/howeyc/gopass
../../../../howeyc/gopass/terminal.go:24:9: undefined: terminal.State
make: *** [Makefile:14: build] Error 2
```

I am thinking this particular problem is the password-prompt for CLI usage.

I really just want to use the diffing & parsing as a lib, as node already has nice password prompt, for example, and has good native postgres client, but also web can't make the requests directly (but it might be cool to have a client side webform that does "here is the SQL to do a diff".)

As a total go-newb, I think it may be a bit beyond me. Would anyone who is good with go want to wrap the lib for wasm-compilation? I'll keep hammering at it, but if you have any suggestions, they'd be much appreciated.

Is this something you want a PR for? I I could also make a node project that exposes it and publishes to npm. I will try to make a wasm/sqldef entry-point and add it to makefile, but again, I'm not the strongest with go, so it might take a while and not be up to snuff :)

**Comment by konsumer** [comment]
I started work on it [over here](https://github.com/konsumer/node-sqldef) as a separate project that will import this lib. This way it can keep up to date, and be self-contained, and the wasm stuff won't mess with this lib at all. It's only boiler-plate now, but when I get it working, I'll publish it on npm.

**Comment by k0kubun** [comment]
It's an interesting project. Thanks for your suggestions.

I don't have an experience supporting wasm target and thus I have no idea how to fix it for now, but if it's only about the password prompt thing, we should be able to fix it without complicating sqldef implementation too much.

I think we should either contribute to https://github.com/howeyc/gopass for wasm support or find something implementing a similar thing and supporting wasm.

**Comment by konsumer** [comment]
> I think we should either contribute to https://github.com/howeyc/gopass for wasm support or find something implementing a similar thing and supporting wasm.

I've got password input & arg-parsing working well in node-space, and postgres/mysql native clients are battle-tested and work pretty well & easily in node (and most other languages.)

I think there will be a lot of things like this that simply won't work in wasm, like the whole native database client stuff, etc. I think the trick will be to just use the SQL diffing part and let the foreign language use it's own libraries for everything else,  so it can take a couple strings of SQL, and just output a string of SQL statements. This way anything that can load wasm (and has it's own postgres client, etc) should work ok. wasm is really limited for network & file operations and things like that: picture the sort of access you have in browser-javascript, but like even less because there's no direct webgl/audio/etc. You can hook into the runtime environment to tell it to do things, but you can't do things like hook into the console directly, or send arbitrary TCP packets.

I am having issues with basic things though, for example wasm won't compile if the `deps` target is left in the makefile (and throws a seemingly unrelated & cryptic error) and this is before I've even imported anything not in the stdlib. If I have more time for it, I'll keep working on it, but it seems like it might just be that go-wasm is in a frustrating not totally functional state right now.

I fought with it for a while, and can't seem to get basic communication between node & go working, once I finally got it compiling at all. I went through a bunch of tutorials, and none seem to work as they should. I've also come to the (possibly incorrect) conclusion that there are some pretty gross things like go forces wasm to use globals to pass data back & forth (even though other languages can compile to wasm that doesn't have this requirement.) I have a feeling I am probly missing some key details, but can't really figure out where to look. It may just be too soon to try to use go with wasm the way I want to, but as I said my familiarity with go is so limited, it's impossible for me to say.

**Comment by konsumer** [comment]
I got a bit closer. Got it generating SQL diffs, but throws obtuse errors on some diffs.

**Comment by konsumer** [comment]
One thing that might make it slightly more robust and elegant would be to figure out how to convert the error to `js.Error()`, and fire the JS callback on an error. I am currently able to print errors in go-space, but couldn't get it to convert them to `js.Error` and send them back to the caller. The wasm-output is also very large. It's 4MB, the way I'm compiling it now, which is way too big for what it does.

It's all so much work (for me) to keep it in golang, I'm starting to wonder if it would just make more sense to simply port `schema.GenerateIdempotentDDLs` to walt/C/rust (for easier compilation to webasm.) Again, it  may be my lack of familiarity, but go+webasm seems really immature and hard to get working well with this approach, at least right now. This library is so useful and rad for all sorts of developers, it really seems like a webasm port would help a lot of people across many language-ecosystems (webasm has bindings for so many languages & environments.)

I'll give it another shot, with [tinygo](https://github.com/tinygo-org/tinygo), which may ease the size & code-pains, but I might have to switch gears soon and just port it to something else.

**Comment by k0kubun** [comment]
You seem to be going in a hard way. Just to be clear, your goal is to make it run on browser (instead of using node.js on console, Electron, etc.), right? 
If you don't need to run it on browser, I'd recommend using sqldef with CLI from node-sqldef, and it would simplify a lot of things.

**Comment by konsumer** [comment]
> You seem to be going in a hard way. 

It definitely feels that way :) I'm hoping it pays off as a learning experience, as early-days phonegap and node ffi experiments helped me understand better how to use the tech, later, even though it was a massive pain.

> Just to be clear, your goal is to make it run on browser (instead of using node.js on console, Electron, etc.), right?

Well, my goal is to compile it to wasm, which can run super-efficiently, in browsers, a few standalone CLIs, node, python, C, go, and many more without being recompiled for different targets/platforms. It's called "web assembly" but really it's just highly constrained & compiled code that runs all over. For example the same wasm-blob that is running [here](http://konsumer.js.org/node-sqldef/) could theoretically be imported into node, python, ruby, a C++ program, run on a CDN edge-worker, directly inside postgres as a stored procedure, PHP, R, Swift, etc. If everything is working well, it compiles to very small binary blobs that run really fast (often faster than the original code, compiled natively.)  I think it's super-cool it runs in the browser, but that isn't the most important part, for me. webasm is like GLSL for CPU stuff. it's cross-device/platform/language, and you can be reasonably sure it will perform well & identically, in general, if you are willing to accept the constraints. It's kinda like compiled java, but it can be used in a bunch of places (other than a JVM compiled for the platform.) I think the future of wasm is "use whatever language you like, then compile it, then run that compiled code anywhere, and interoperate with any other ecosystems you need to." We are getting kinda close, but it's still not quite there.

I have a feeling in my case, I am including debugging symbols, and the go-wasm stuff isn't tree-shaking dead code related to the console and databases, and other oddities I don't fully understand, on the go-wasm side. There are probly lots of other things, as I am so new to go and especially go-wasm. I am probly also doing it very wrong, and because of that am getting cryptic errors that are hard to troubleshoot or reason about.

> If you don't need to run it on browser, I'd recommend using sqldef with CLI from node-sqldef, and it would simplify a lot of things.

Yeh totally. That would definitely be so much simpler. My most immediate thought about how to use sqldef in node was to just do a npm `postinstall` to grab the platform/arch compiled for the sqldef CLI directly from your github releases and wrap it with an exec call. I actually did this with a [node-wrapper for ffmpeg](https://www.npmjs.com/package/easy-ffmpeg). One of the downsides is that I end up troubleshooting and supporting the runtimes and maintaining the builds, and it can be tricky or impossible to find/build the bin for every platform/arch, that has all the same features. pi on old linux distros, for example, can be a real pain to support. You can also just tell users "now go install this cli thing in your path", but I really dig having all my deps in a single definition, and have it all work without having to go ensure dependencies manually, or stop to go install things in some other ecosystem.

If I can't figure it out, and no go-wasm gurus are available that want to help, I may just end up doing the CLI-wrapper, though. It would be lots easier than porting it or the wasm issues, by a lot. Also your CLI works really well. Efficient, friendly, and to the point.

I was really hoping that it would be easier, and once figured out, it would just be solved and simple. It actually seems to throw less errors on the web than in nodejs (I think related to go's wasm concept of an "application" vs a lib, which makes the run-loop important.) Maybe I should just use what I've got for the rare web use-cases, and stick with a wrapper around your CLI, at least until things get easier in go with wasm. I can try to integrate the wasm build into your setup as a PR, maybe just as a seperate Makefile target that doesn't depend on `deps`.

**Comment by konsumer** [comment]
I PR'd the build target, and basic web-based demo (you could put it in gh-pages for a cool interactive demo, if you want.) I think I will switch gears, and just wrap the CLI for node. Maybe I'll check back in on go-wasm later, and see if it works better. Thanks for putting up with all the back-and-forth and outloud thinking.

**Comment by k0kubun** [comment]
> I think I will switch gears, and just wrap the CLI for node

That sounds sensible if it works for your use case.

> Maybe I'll check back in on go-wasm later, and see if it works better.

So, this bit of work https://github.com/k0kubun/sqldef/pull/46 is not meant to be maintained and your filed it for the record? Then, maybe https://github.com/k0kubun/sqldef/pull/46#issuecomment-549008836 may not meet what you wanted.

Still, I'm okay to keep your work as github.com/sqldef/sqldef-wasm in case we check that back in the future. Do you want me to create the repository and keep your wasm work there?

**Comment by konsumer** [comment]
> That sounds sensible if it works for your use case.

I think it will totally work. I got all excited about go+wasm, but it's really not the actual thing I need, day-to-day.

> So, this bit of work #46 is not meant to be maintained and your filed it for the record? Then, maybe #46 (comment) may not meet what you wanted.

I figure the work is still useful, especially as a demo of your tool, but probly not the way I intended (as a general way to package the SQL diffing code for everyone.)

> Still, I'm okay to keep your work as github.com/sqldef/sqldef-wasm in case we check that back in the future. Do you want me to create the repository and keep your wasm work there?

Totally up to you, if you think it's useful for others, or think it might move in that direction, later. I'm also happy to just move my repo to be just the CLI wrapper for node, and let the web dir + wasm Makefile target live over here.

**Comment by k0kubun** [comment]
I moved your https://github.com/k0kubun/sqldef/pull/46 to https://github.com/sqldef/sqldef-wasm.

> I'm also happy to just move my repo to be just the CLI wrapper for node, and let the web dir + wasm Makefile target live over here.

In case you want to move your node-sqldef to there, I invited you as an organization owner.
