### ISSUE TITLE
VARCHAR BINARY does not work.

### ISSUE THREAD

**Issue by timakin** [k0kubun/sqldef#47]
An attachment of `BINARY` option to a VARCHAR-typed column does not work well.
For example,

## Current schema
```
CREATE TABLE `ng_words` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word` varchar(64) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

## New one
```
CREATE TABLE `ng_words` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word` varchar(64) BINARY NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

This difference displays the alert that `binary` is a syntax error..
Maybe current sqldef can parse `VARBINARY`, but it cannot for `varchar(xx) BINARY` syntax.

```
found syntax error when parsing DDL "CREATE TABLE `ng_words` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word` varchar(64) BINARY NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4": syntax error at position 103 near 'binary'
```

**Comment by k0kubun** [comment]
I figured out how we can support it. I'll leave a note for now:

To support MySQL's BINARY attribute https://dev.mysql.com/doc/refman/8.0/en/string-type-overview.html correctly, it seems that we need to do:

1. Parse `CREATE TABLE`'s CHARSET properly, falling back to default charset if not specified in DDL.
2. Parse column's collate (and maybe charset as well) and support altering them.
3. Parse `BINARY` where we find `COLLATE ID`, and replace the `BINARY` attribute with `COLLATE {{default charset}}_bin`.

**Comment by k0kubun** [comment]
It's not a perfect implementation yet, but at least I supported the provided example in v0.6.1. Could you try it once [the release](https://travis-ci.org/github/k0kubun/sqldef/builds/705236902) is completed?
