### ISSUE TITLE
Changing a column into 'DEFAULT CURRENT_TIMESTAMP' does not work.

### ISSUE THREAD

**Issue by uechoco** [k0kubun/sqldef#50]
## Step to reproduce

My environment:

* MySQL Server version: 5.7.28 Homebrew
* [mysqldef v0.5.9](https://github.com/k0kubun/sqldef/releases/download/v0.5.9/mysqldef_darwin_amd64.zip)

Step1. Create database

```sql
CREATE DATABASE IF NOT EXISTS `test01` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

Step2. Initialize table

```sql
CREATE TABLE `tools` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

Step3. Write schema.sql file.

```sql
CREATE TABLE `tools` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

* `created_at` : added `DEFAULT CURRENT_TIMESTAMP`
* `updated_at` : added `DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`

Step4. Do mysqldef, but it does not recoginze modified 'created_at'.

```
$ ./mysqldef -uroot --file=schema.sql --dry-run test01
-- dry run --
ALTER TABLE tools CHANGE COLUMN updated_at updated_at datetime NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp;

$ ./mysqldef -uroot --file=schema.sql test01
-- Apply --
ALTER TABLE tools CHANGE COLUMN updated_at updated_at datetime NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp;
```

**Comment by k0kubun** [comment]
Thank you for the good reporting. I think I fixed this scenario in https://github.com/k0kubun/sqldef/commit/c82b8c1e6ad0ec1c3d9bd45d84b7182ff12f2bde.

Please try v0.5.10 which is being released here https://travis-ci.org/k0kubun/sqldef/builds/629558542.

**Comment by uechoco** [comment]
What a wonderful speedy fixing! Thanks a lot.
