### ISSUE TITLE
Please let us install with a package manager like brew or apt-get

### ISSUE THREAD

**Issue by bionicles** [k0kubun/sqldef#52]
to test migrations in my CI/CD pipelines as a devops guy I like to be able to install the database migration tool with brew or apt-get command line tool 

would it be possible to put the releases up in these package managers?

another option would be to put a one liner shell command on the README file, but it seems you have done the work to make this work on mac / os / linux and I would be unsure how to write a script which would work on all of these rigs

thank you for making sqldef, it is a handy tool for postgres users to version control their schemas

**Comment by k0kubun** [comment]
> would it be possible to put the releases up in these package managers?

Sure, if it's only about brew and apt-get, I can take a look. Give me some time before preparing it though.

> another option would be to put a one liner shell command on the README file
>
> I would be unsure how to write a script which would work on all of these rigs

One option for it might be preparing Dockerfile like https://github.com/guitarrapc/docker-mysqldef for psqldef and using it.

While it's not one liner that works for all, another option would be just:

```sh
# Linux
wget -O - https://github.com/k0kubun/sqldef/releases/download/v0.5.11/psqldef_linux_amd64.tar.gz | tar xvz
./psqldef ...

# macOS
curl -o psqldef.zip -sL https://github.com/k0kubun/sqldef/releases/download/v0.5.11/psqldef_darwin_amd64.zip
unzip psqldef.zip
./psqldef ...
```

I hope this works for you for the time being.

**Comment by k0kubun** [comment]
I supported installation by brew https://github.com/sqldef/homebrew-sqldef, and I explained the instructions at https://github.com/k0kubun/sqldef#distributions.

I haven't implemented apt-get support yet, but I believe the command explained there is usually sufficient. For your "unsure how to write a script which would work on all of these" problem, for now I prepared a script for you:

```bash
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64)  arch=amd64 ;;
  aarch64) arch=arm64 ;;
esac
wget -O - "https://github.com/k0kubun/sqldef/releases/latest/download/psqldef_${os}_${arch}.tar.gz" | tar xvz
```
