### ISSUE TITLE
Changing the column combination of the index does not work

### ISSUE THREAD

**Issue by uechoco** [k0kubun/sqldef#53]
## Step to reproduce

My environment:

* MySQL Server version: 5.7.28 Homebrew
* mysqldef v0.5.10

Step1. Create database

```sql
CREATE DATABASE IF NOT EXISTS `test01` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

Step2. Initialize table

```sql
CREATE TABLE `tools` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `type` int(10) unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_tools_01` (`created_at`),
  KEY `index_tools_02` (`name`, `type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

Step3. Write schema.sql file.

```sql
CREATE TABLE `tools` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `type` int(10) unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_tools_01` (`created_at`, `updated_at`),
  KEY `index_tools_02` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

* changed `index_tools_01` columns
* changed `index_tools_02` columns

Step4. Do mysqldef, but it does not recoginze modified two index

```
$ ./mysqldef -uroot --file=schema.sql --dry-run test01
-- Nothing is modified --
```

(Step5. If I change the index name in advance, it worked normally)

* login mysql
* use `test01` database
* rename `index_tools_01` with  `index_tools_03`
* rename `index_tools_02` with  `index_tools_04`
* do mysqldef (step4)

```
$ ./mysqldef -uroot --file=schema.sql --dry-run test01
-- dry run --
ALTER TABLE tools ADD key index_tools_01(created_at, updated_at);
ALTER TABLE tools ADD key index_tools_02(name);
ALTER TABLE tools DROP INDEX index_tools_03;
ALTER TABLE tools DROP INDEX index_tools_04;
```

------

Are these also sqldef [limitations](https://github.com/k0kubun/sqldef#limitations) ?

**Comment by k0kubun** [comment]
It would be considered as a limitation that sqldef does not generate `RENAME INDEX` here.

However, generating `-- Nothing is modified --` is a bug. I fixed sqldef to detect the change properly in https://github.com/k0kubun/sqldef/commit/7e4a2dd53116551e9cb1d7e57f5d13a962c08e89 and it now generates `DROP INDEX` + `ADD INDEX`, while I'm not sure if you really wanted that. Please try v0.5.12 which is being released at https://travis-ci.org/k0kubun/sqldef/builds/643693973.

**Comment by uechoco** [comment]
This is what I'd wanted! Thank you as always!!
