### ISSUE TITLE
idempotent way to update FK constraints?

### ISSUE THREAD

**Issue by ryota-ka** [k0kubun/sqldef#54]
Hello,

Is there any plan to support `ON DELETE` and `ON UPDATE` options for foreign key constraints?

I believe they're relatively popular features in schema definition.
(for an instance, I remember [ActiveRecord](https://rubygems.org/gems/activerecord/) supports them with `add_foreign_key`.)

---

MySQL:
https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html

PostgreSQL:
https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK

---

Thank!

**Comment by k0kubun** [comment]
When you file an issue, please make sure you describe what you want to do, which would be "original schema" + "input of mysqldef or psqldef" + "generated DDL you expect" in this repository like https://github.com/k0kubun/sqldef/issues/53, not just why you want.

I can see `FOREIGN KEY` with `ON DELETE` / `ON UPDATE` in test cases. You seem to assume "`ON DELETE` and `ON UPDATE` options for foreign key constraints" are entirely not supported, but it doesn't seem to be the case. Perhaps adding/removing `ON UPDATE` / `ON DELETE`? I'd like to know the exact case you actually tried first.

**Comment by ryota-ka** [comment]
@k0kubun Oops, sorry for bothering.

> You seem to assume "`ON DELETE` and `ON UPDATE` options for foreign key constraints" are entirely not supported,

I did. I should have take a look into repo to check the implementation already exists.

---

After further investigation, I've noticed that the reason I got confused is that `ON DELETE` option won't be added to the existing FK constraint when rewriting the schema.

Here's minimal way to reproduce the problem (with MySQL):

<details>

```sql
mysql> CREATE DATABASE test;
```

```sh
$ mysqldef -h mysql -u root test --file ./schema.sql
-- Apply --
CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `recipes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

where `schema.sql` is:

```sql
CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `recipes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

After that, rewrite `schema.sql` ,

```diff
--- a/schema.sql
+++ b/schema.sql
@@ -7,5 +7,5 @@ CREATE TABLE `recipes` (
   `id` int(11) NOT NULL,
   `user_id` int(11) NOT NULL,
   PRIMARY KEY (`id`),
-  CONSTRAINT `recipes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
+  CONSTRAINT `recipes_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

Applying the schema again,

```sh
$ mysqldef -h mysql -u root test --file ./schema.sql
-- Nothing is modified --
```

At first I expected that `ON DELETE` option will be applied.

</details>

But I've realized that, to achieve that, we have to delete the target FK constraint once and the re-add one with the specified option.
So I feel perhaps it may be out-of-scope of this project. (WDYT?)
(Additionally, if yes, do you have any good practice/workaround to achieve this?)

Sorry for bothering again, and thanks!

**Comment by k0kubun** [comment]
A similar thing for index is implemented as "delete" + "re-add" like you said. I implemented a similar thing for foreign key too. Please try v0.5.14 being released at https://travis-ci.org/k0kubun/sqldef/builds/657087387.
