### ISSUE TITLE
Support jsonb

### ISSUE THREAD

**Issue by apatil** [k0kubun/sqldef#55]
`GenerateIdempotentDDLs` fails with a syntax error if a table contains a Postgres jsonb column. I'm guessing that is because sqlparser supports [json](https://github.com/xwb1989/sqlparser/blob/120387863bf27d04bc07db8015110a6e96d0146c/dependency/sqltypes/type.go#L141) but not jsonb.

To support jsonb in sqldef, would one need to patch sqlparser, or is there a simpler way?

**Comment by k0kubun** [comment]
Your guess is correct. Though sqlparser was originally compatible with MySQL and therefore we already forked it for Postgres support.

I fixed it in v0.5.13. Could you try it once it's released by https://travis-ci.org/k0kubun/sqldef/builds/656573588?

**Comment by apatil** [comment]
It seemed to work. Thanks!
