### ISSUE TITLE
Not found mysqldef_darwin_amd64.zip and psqldef_darwin_386.zip in v0.5.14 release.

### ISSUE THREAD

**Issue by locona** [k0kubun/sqldef#56]
The following is not found in the release of v0.5.14.

diff 
- mysqldef_darwin_amd64.zip
- psqldef_darwin_386.zip

### v0.5.14
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/18649881/76390541-f1c78480-63b0-11ea-8ff0-29d1b683e54b.png">

### v0.5.13
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/18649881/76390749-4e2aa400-63b1-11ea-995b-e80855018a44.png">

**Comment by locona** [comment]
thank you

**Comment by k0kubun** [comment]
Oh sorry, I had forgotten to notify you as I was concurrently doing another thing 😅 

Yes those files experienced upload failures, and I needed to delete failed uploads and then retrying Travis fixed the issue. Thank you for your report.
