### ISSUE TITLE
Postgres Array type doesn't work

### ISSUE THREAD

**Issue by vgiverts** [k0kubun/sqldef#58]
My schema uses Postgres Arrays and I was getting an error when attempting a dry run. The test case schema is simply:

`CREATE TABLE public.users (
    id integer NOT NULL,
    arr ARRAY
)`

The export works fine
`/psqldef test --export > schema.sql`

But the --dry-run fails
`/psqldef test --dry-run < schema.sql`

I get:
 _syntax error at position 67 near 'ARRAY'_

**Comment by k0kubun** [comment]
Thanks for reporting. Let me confirm this first: You intended to use something like `arr integer ARRAY`, right?

**Comment by k0kubun** [comment]
Your exact test case didn't work on my Postgres:

```sql
test=# CREATE TABLE public.users ( id integer NOT NULL, arr ARRAY );
ERROR:  syntax error at or near "ARRAY"
LINE 1: ...REATE TABLE public.users ( id integer NOT NULL, arr ARRAY );
                                                               ^
```

But I fixed the issue for types like `integer array`, `integer[]`, etc. Please try v0.5.18.
