### ISSUE TITLE
syntax error for pg_buffercache

### ISSUE THREAD

**Issue by strogiyotec** [k0kubun/sqldef#65]
## Problem
Good day, this is my problem, I have a postgres module called `pg_buffercache` that checks what is happening with shared buffers, I made a dump of database schema, hereis the result of this command `./psqldef -U postgres -W 123 test_cache --export`
```
CREATE TABLE public.test (
    id integer
);

CREATE TABLE public.pg_buffercache (
);
```
After that I modified test table by adding new column 'name test' then I execute `/psqldef -U postgres -W 123 test_cache --dry-run < schema.sql` and this is the output
```
found syntax error when parsing DDL "CREATE TABLE public.pg_buffercache (
)": syntax error at position 39
```
## Expected
I expect it to show me new column
### Initial schema
Provided above

Postgres version
```
psql (PostgreSQL) 12.4 (Ubuntu 12.4-1.pgdg18.04+1)
```

Thanks in advance

**Comment by k0kubun** [comment]
Thanks, I think I fixed the issue and [started](https://travis-ci.org/github/k0kubun/sqldef/builds/732649201) the release of v0.7.1 including the fix.

**Comment by strogiyotec** [comment]
Awesome, thanks for your time
