### ISSUE TITLE
syntax error on float column with negative default value

### ISSUE THREAD

**Issue by bennlich** [k0kubun/sqldef#66]
## Problem

mysqldef throws a syntax error when trying to parse a table schema with a float column that has a negative default value

e.g.:

    `positionZ` float DEFAULT -20

**Comment by k0kubun** [comment]
Thanks, I fixed it and [started releasing v0.7.3](https://travis-ci.org/github/k0kubun/sqldef/builds/736252064).

**Comment by bennlich** [comment]
Thank you!
