### ISSUE TITLE
mysqldef does not notice when you change a column's DEFAULT value

### ISSUE THREAD

**Issue by bennlich** [k0kubun/sqldef#67]
## Problem

E.g. if your schema has `positionZ float DEFAULT -20`, and you change to `positionZ float DEFAULT 100`, mysqldef says:

```
-- Nothing is modified --
```

I see the same behavior for int, varchar, and timestamp column defaults. The only time mysqldef noticed a change to a default value was when I went from DEFAULT NULL to a non-null value.

**Comment by k0kubun** [comment]
:+1: Fixed it at v0.7.4.
