### ISSUE TITLE
AUTO_INCREMENT disappears when changing column type

### ISSUE THREAD

**Issue by hiroyuki-kamei** [k0kubun/sqldef#70]
## Problem
When changing the data type of a column with AUTO_INCREMENT, the ALTER statement does not have AUTO_INCREMENT.
Therefore, AUTO_INCREMENT disappears.

Also, running mysqldef again with the same input DDL will run the DDL you expect.

### Initial schema
```
| sample | CREATE TABLE `sample` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) NOT NULL,
  `password` char(128) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_id` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
```

### Input DDLs
```
CREATE TABLE `sample` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `password` char(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_id` (`member_id`)
);
```

### Result of mysqldef
```
-- Apply --
ALTER TABLE sample CHANGE COLUMN id id bigint NOT NULL;
```

### Output DDLs
```
| sample | CREATE TABLE `sample` (
  `id` bigint(20) NOT NULL,
  `member_id` int(11) NOT NULL,
  `password` char(128) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_id` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
```

### Supplement
Running mysqldef again with the same input DDL will run the DDL you expect.

#### Result of mysqldef (Second time)
```
-- Apply --
ALTER TABLE sample CHANGE COLUMN id id bigint NOT NULL AUTO_INCREMENT;
```

#### Output DDLs (Second time)
```
| sample | CREATE TABLE `sample` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `member_id` int(11) NOT NULL,
  `password` char(128) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `member_id` (`member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
```

**Comment by k0kubun** [comment]
Thanks to report this! This was a bug caused by another fix for PRIMARY KEY https://github.com/k0kubun/sqldef/commit/1ae0dd3793aad595b34c088d72dff5409fb482ee. Now I [started the release of v0.7.6](https://travis-ci.org/github/k0kubun/sqldef/builds/738490389) fixing the bug.

**Comment by hiroyuki-kamei** [comment]
Thanks for fixing the bug! I 
Confirmed that it was the expected movement in v0.7.6.

Thank you for your quick reaction.
