### ISSUE TITLE
howeyc/gopass is deprecated 

### ISSUE THREAD

**Issue by uta-mori** [k0kubun/sqldef#73]
## Problem

The authors of the howeyc/gopass  library are encouraging to use [x/crypto/ssh/terminal](https://pkg.go.dev/golang.org/x/crypto/ssh/terminal) instead:

> You should probably just use terminal.

--- 

## Migration

```diff
	if opts.Prompt {
		fmt.Printf("Enter Password: ")
-		pass, err := gopass.GetPasswd()
+               pass, err := terminal.ReadPassword(syscall.Stdin)
		if err != nil {
			log.Fatal(err)
		}
		password = string(pass)
	}
```

**Comment by k0kubun** [comment]
Is https://github.com/k0kubun/sqldef/commit/7f2771676af21fa9b43bc7622d27646c41f7e4e7 what you imagined?

**Comment by uta-mori** [comment]
@k0kubun 

I'm sorry.
In addition, you'll need the following

- import dependencies
- `go mod tidy`

```diff
import (
	"fmt"
	"log"
	"os"
+	"syscall"

-	"github.com/howeyc/gopass"
	"github.com/jessevdk/go-flags"
	"github.com/k0kubun/sqldef"
	"github.com/k0kubun/sqldef/adapter"
	"github.com/k0kubun/sqldef/adapter/mysql"
	"github.com/k0kubun/sqldef/schema"
+	"golang.org/x/crypto/ssh/terminal"
)
```

**Comment by k0kubun** [comment]
Thanks :pray: I've formatted my machine recently, so my machine is not ready for running tests locally :sweat_smile: https://github.com/k0kubun/sqldef/commit/c6d08efdc87eb503a0e20f9f406e98eff5bc023d
