### ISSUE TITLE
psqldef syntax error on REFERENCES FK constraint

### ISSUE THREAD

**Issue by AriaFallah** [k0kubun/sqldef#82]
## Problem
I can't define foreign key relationships using `REFERENCES` because I get

```
found syntax error when parsing DDL "CREATE TABLE b (
  b_id INTEGER PRIMARY KEY,
  a_id INTEGER REFERENCES a
)": syntax error at position 71 near 'references'
```

Running the same code directly in `psql` works though! I'm using the following command to run psqldef

```
PGSSLMODE=disable psqldef -h localhost -U postgres -W verysecure postgres --dry-run < ./db/schema.sql
```

### Initial schema
Blank!

### Input DDLs
```sql
CREATE TABLE a (
  a_id INTEGER PRIMARY KEY 
);

CREATE TABLE b (
  b_id INTEGER PRIMARY KEY,
  a_id INTEGER REFERENCES a
);
```

### Output DDLs
None 😢

**Comment by k0kubun** [comment]
I fixed this particular case in v0.8.3, which is being [released](https://github.com/k0kubun/sqldef/actions/runs/404944748).

**Comment by AriaFallah** [comment]
This is crazy fast work! Thanks a ton. Is there anywhere I could donate to this project?

**Comment by k0kubun** [comment]
Thank you :) https://github.com/sponsors/k0kubun would be the best place for it.

**Comment by AriaFallah** [comment]
Signed up! Never written Ruby so idk about the JIT stuff, but I love your work here :)

**Comment by k0kubun** [comment]
Thank you so much for sponsoring me :heart_eyes:
