### ISSUE TITLE
psqldef syntax error on DEFAULT NOW() for timestamp fields

### ISSUE THREAD

**Issue by AriaFallah** [k0kubun/sqldef#83]
## Problem
I can't set the default value of timestamp fields because I get

```
 found syntax error when parsing DDL "CREATE TABLE a (
  a_id INTEGER PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT NOW()
)": syntax error at position 81 near 'NOW'
```

Running the same code directly in `psql` works though! I'm using the following command to run psqldef

```
PGSSLMODE=disable psqldef -h localhost -U postgres -W verysecure postgres --dry-run < ./db/schema.sql
```

### Initial schema
Blank!

### Input DDLs
```sql
CREATE TABLE a (
  a_id INTEGER PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT NOW()
);
```

### Output DDLs
None 😢 

## Workaround
Changing from `NOW()` to `CURRENT_TIMESTAMP` works so I'm guessing the issue is the `()`?

```sql
CREATE TABLE a (
  a_id INTEGER PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

**Comment by k0kubun** [comment]
It seems it's already supported since https://github.com/k0kubun/sqldef/pull/80. Please use v0.8.2.

**Comment by AriaFallah** [comment]
Thank you! I was using whatever version was in homebrew, which I guess is out of date. I'll pull from github releases instead!

**Comment by k0kubun** [comment]
:grimacing: TBH I've forgotten I maintain it. Maybe I should automate bumping the version in the formula. In the meantime, I manually updated the version https://github.com/sqldef/homebrew-sqldef/commit/5d1efb4dd5b63ad0fbb9d5e1851837358c6e9387.

**Comment by k0kubun** [comment]
Automated it https://github.com/k0kubun/sqldef/commit/ad43ea13d54761253ea9dffb4e0cf667676c9d39. I'll test it at v0.8.3.
