### ISSUE TITLE
psqldef syntax error on many-to-many table "CONSTRAINT a_b_pkey PRIMARY KEY (a_id, b_id)"

### ISSUE THREAD

**Issue by AriaFallah** [k0kubun/sqldef#88]
## Problem
I can't create a many-to-many table with a primary key constraint because I get

```
found syntax error when parsing DDL "CREATE TABLE a_b (
  a_id INTEGER REFERENCES a,
  b_id INTEGER REFERENCES b,
  CONSTRAINT a_b_pkey PRIMARY KEY (a_id, b_id)
)": syntax error at position 107 near 'primary'
```

Running the same code directly in `psql` works though! I'm using the following command to run psqldef

```
PGSSLMODE=disable psqldef -h localhost -U postgres -W verysecure postgres --dry-run < ./db/schema.sql
```

### Initial schema
Blank!

### Input DDLs
```sql
CREATE TABLE a (
  id SERIAL PRIMARY KEY
);

CREATE TABLE b (
  id SERIAL PRIMARY KEY
);

CREATE TABLE a_b (
  a_id INTEGER REFERENCES a,
  b_id INTEGER REFERENCES b,
  CONSTRAINT a_b_pkey PRIMARY KEY (a_id, b_id)
);
```

### Output DDLs
None 😢

**Comment by k0kubun** [comment]
dumb question: What is different between `CONSTRAINT a_b_pkey PRIMARY KEY (a_id, b_id)` and just `PRIMARY KEY (a_id, b_id)`? Why do you need to also specify `CONSTRAINT a_b_pkey`?

**Comment by AriaFallah** [comment]
Er probably because it's top stackoverflow answer so I never knew there was another way 😄. Been doing it like this for a while

https://stackoverflow.com/questions/9789736/how-to-implement-a-many-to-many-relationship-in-postgresql

**Comment by k0kubun** [comment]
OK, thank you for sharing it. I'll try supporting it by handling it like the normal primary key, but please give me some time until Dec 25th, the Ruby 3 release day, because we have the workaround.

**Comment by AriaFallah** [comment]
Take your time, and take a break for the holiday! Thanks for looking into this

**Comment by k0kubun** [comment]
I released a fix to make it work like the normal primary key in v0.8.7.
