### ISSUE TITLE
[psqldef] [export] incorrect DDL

### ISSUE THREAD

**Issue by ackintosh** [k0kubun/sqldef#96]
## Problem

I got the DDL below when run psqldef --export on a table which has **composite primary key.**

```sql
CREATE TABLE main.test_table (
    "col1" character varying(40) NOT NULL PRIMARY KEY,
    "col2" character varying(6) NOT NULL PRIMARY KEY,
    "created_at" timestamp NOT NULL
);
CREATE UNIQUE INDEX test_table_pk ON main.test_table USING btree (col1, col2);
```

Unfortunately it is incorrect, it is failed to run psqldef with the DDL. 😢 

```
2021/02/08 06:43:58 pq: multiple primary keys for table "test_table" are not allowed
```

## Expected

```sql
CREATE TABLE main.test_table (
    "col1" character varying(40) NOT NULL,
    "col2" character varying(6) NOT NULL,
    "created_at" timestamp NOT NULL,
    PRIMARY KEY (col1, col2)
);
```

**Comment by k0kubun** [comment]
I'm going to fix this, but a behavior I reproduced was slightly different from your report. It didn't generate `CREATE UNIQUE INDEX`.

```sql
$ cat /tmp/a.sql
CREATE TABLE main.test_table (
    "col1" character varying(40) NOT NULL,
    "col2" character varying(6) NOT NULL,
    "created_at" timestamp NOT NULL,
    PRIMARY KEY (col1, col2)
);

$ psql -Upostgres -h 127.0.0.1 test < /tmp/a.sql
CREATE TABLE

$ PGSSLMODE=disable go run cmd/psqldef/psqldef.go -Upostgres -h 127.0.0.1 test --export
CREATE TABLE main.test_table (
    "col1" character varying(40) NOT NULL PRIMARY KEY,
    "col2" character varying(6) NOT NULL PRIMARY KEY,
    "created_at" timestamp NOT NULL
);
```

What psqldef version are you using? If it's the latest, is there any other DDL you used for the table?

**Comment by k0kubun** [comment]
Anyhow, I fixed what I could reproduce in https://github.com/k0kubun/sqldef/commit/e2ee40cda74e5341bdd9fa4e8050b8b691547527, and started a release as v0.8.8.

**Comment by ackintosh** [comment]
Thank you for your quick response!

Hmm, a DDL I exported now again is same as the one you reproduced, which has no `CREATE UNIQUE INDEX`. Sorry, it was a copy and paste mistake. 💦
